# server
port: ":8081"
read_header_timeout: 3s
read_timeout: 5s
write_timeout: 0s
idle_timeout: 15s
max_retries: 5
delay_retries: "2s"

# data-generator
generator_stream_url: "http://data-generator:8080/api/v1/data/stream"
generator_batch_url: "http://data-generator:8080/api/v1/data/batch"
mode: "both"
batch_size: 10
interval: 2
account: true
event_type: "PASSWORD_CHANGED"
fraud: true
fraud_score: 50
country_code: "POLAND"
device_type: "MOBILE"
transaction: true
amount: 1000.0
currency: "PLN"
status: "FAILED"
payment_type: "BANK_TRANSFER"

# mongo
database_name: "event_driver"
stream_collection: stream_data
batch_collection: batch_data
